//PRODUCTS
export const SET_LIST_PRODUCTS = 'SET_LIST_PRODUCTS';
export const SET_LIST_PRODUCTS_LOADING = 'SET_LIST_PRODUCTS_LOADING';
export const SET_LIST_PRODUCTS_ERROR = 'SET_LIST_PRODUCTS_ERROR';
