//PRODUCTS
export const SET_PRODUCT = 'SET_PRODUCT';
export const SET_LIST_PRODUCTS = 'SET_LIST_PRODUCTS';
export const SET_LIST_CATEGORIES_PRODUCTS = 'SET_LIST_CATEGORIES_PRODUCTS';
export const SET_PRODUCT_LOADING = 'SET_PRODUCT_LOADING';
export const SET_PRODUCT_ERROR = 'SET_PRODUCT_ERROR';
