//PRODUCTS
export const SET_PRODUCT = 'SET_PRODUCT';
export const SET_LIST_PRODUCTS = 'SET_LIST_PRODUCTS';
export const SET_LIST_CATEGORIES_PRODUCTS = 'SET_LIST_CATEGORIES_PRODUCTS';
export const SET_PRODUCT_LOADING = 'SET_PRODUCT_LOADING';
export const SET_PRODUCT_ERROR = 'SET_PRODUCT_ERROR';

//USER

export const SET_USER = 'SET_USER';
export const SET_LIST_USERS = 'SET_LIST_USERS';
export const SET_USER_LOADING = 'SET_USER_LOADING';
export const SET_USER_ERROR = 'SET_USER_ERROR';
